<%namespace name="conf" file="provision.conf.mako"/>\
<%namespace name="sh" file="provision.sh.mako"/>\
<%def name="render(x=0)">\
  notcompute:
    Metadata:
      os-collect-config:
        cfn:
          access_key_id:
            Ref: Key
          path: notcomputeConfig.Metadata
          secret_access_key:
            Fn::GetAtt:
            - Key
            - SecretAccessKey
          stack_name:
            Ref: AWS::StackName
    Properties:
      flavor:
        Ref: Flavor
      image:
        Ref: notcomputeImage
      key_name:
        Ref: KeyName
    Type: OS::Nova::Server
  notcomputeConfig:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /root/tuskar/provision.conf:
              content:
                Fn::Base64:
                  |
<% conf.render() %>\
              mode: "000644"
              owner: root
              group: root
            /root/tuskar/provision.sh:
              content:
                Fn::Base64:
                  |
<% sh.render() %>\
              mode: "000700"
              owner: root
              group: root
      OpenStack::Heat::Stack: {}
      Openstack::ImageBuilder::Elements:
      - boot-stack
      - heat-cfntools
      - heat-localip
      - neutron-network-node
      admin-password:
        Ref: AdminPassword
      admin-token:
        Ref: AdminToken
      cinder:
        db: mysql://cinder:unset@localhost/cinder
        service-password:
          Ref: CinderPassword
        volume_size_mb: '5000'
      controller-address:
        Fn::Select:
        - 0
        - Fn::Select:
          - ctlplane
          - Fn::GetAtt:
            - notcompute
            - networks
      db-password: unset
      glance:
        db: mysql://glance:unset@localhost/glance
        host:
          Fn::Select:
          - 0
          - Fn::Select:
            - ctlplane
            - Fn::GetAtt:
              - notcompute
              - networks
        service-password:
          Ref: GlancePassword
      heat:
        admin_password:
          Ref: HeatPassword
        admin_tenant_name: service
        admin_user: heat
        auth_encryption_key: unset___________
        db: mysql://heat:unset@localhost/heat
        heat_watch_server_url:
          Fn::Join:
          - ''
          - - http://
            - Fn::Select:
              - 0
              - Fn::Select:
                - ctlplane
                - Fn::GetAtt:
                  - notcompute
                  - networks
            - :8003
        metadata_server_url:
          Fn::Join:
          - ''
          - - http://
            - Fn::Select:
              - 0
              - Fn::Select:
                - ctlplane
                - Fn::GetAtt:
                  - notcompute
                  - networks
            - :8000
        waitcondition_server_url:
          Fn::Join:
          - ''
          - - http://
            - Fn::Select:
              - 0
              - Fn::Select:
                - ctlplane
                - Fn::GetAtt:
                  - notcompute
                  - networks
            - :8000/v1/waitcondition
      interfaces:
        control: eth0
      keystone:
        db: mysql://keystone:unset@localhost/keystone
        host:
          Fn::Select:
          - 0
          - Fn::Select:
            - ctlplane
            - Fn::GetAtt:
              - notcompute
              - networks
      neutron:
        host:
          Fn::Select:
          - 0
          - Fn::Select:
            - ctlplane
            - Fn::GetAtt:
              - notcompute
              - networks
        metadata_proxy_shared_secret: unset
        ovs:
          enable_tunneling: 'True'
          local_ip:
            Fn::Select:
            - 0
            - Fn::Select:
              - ctlplane
              - Fn::GetAtt:
                - notcompute
                - networks
          physical_bridge: br-ex
          public_interface: eth0
          tenant_network_type: gre
        ovs_db: mysql://neutron:unset@localhost/ovs_neutron?charset=utf8
        service-password:
          Ref: NeutronPassword
      nova:
        compute_driver: libvirt.LibvirtDriver
        db: mysql://nova:unset@localhost/nova
        host:
          Fn::Select:
          - 0
          - Fn::Select:
            - ctlplane
            - Fn::GetAtt:
              - notcompute
              - networks
        metadata-proxy: true
        service-password:
          Ref: NovaPassword
      os-collect-config:
        cfn:
          access_key_id:
            Ref: Key
          path: notcomputeConfig.Metadata
          secret_access_key:
            Fn::GetAtt:
            - Key
            - SecretAccessKey
          stack_name:
            Ref: AWS::StackName
      rabbit:
        host:
          Fn::Select:
          - 0
          - Fn::Select:
            - ctlplane
            - Fn::GetAtt:
              - notcompute
              - networks
        password: guest
    Properties:
      ImageId: '0'
      InstanceType: '0'
      AvailabilityZone: nova::${x}
      UserData:
        Fn::Base64:
          |
          #!/bin/bash -v
          /opt/aws/bin/cfn-init
          # We need to set the undercloud Heat IP in the boto config.  Atm this
          # is hardcoded.  We should set a hostname in the tuskar conf.
          sed -e "s/0.0.0.0/192.0.2.2/g" /var/lib/heat-cfntools/cfn-boto-cfg > /tmp/cfn-boto-cfg
          mv -f /tmp/cfn-boto-cfg /var/lib/heat-cfntools/cfn-boto-cfg
          exec /root/tuskar/provision.sh &> /root/tuskar/provision.log &
    Type: AWS::AutoScaling::LaunchConfiguration
</%def>\
